### ISSUE TITLE
Cannot Pass a Cookie

### ISSUE THREAD

**Issue by redreceipt** [proyecto26/react-native-inappbrowser#105]
Trying to pass a cookie through the headers, I know it's correct going into the function but it doesn't seem to be making it to the browser correctly, is there anything obviously wrong with this implementation?

<img width="1088" alt="Screen Shot 2019-09-10 at 11 51 50 AM" src="https://user-images.githubusercontent.com/2659478/64629665-a14f7a00-d3c1-11e9-8631-576118259741.png">

**Comment by jdnichollsc** [comment]
**headers** is a property only for Android

**Comment by redreceipt** [comment]
is there a way to set a cookie in iOS?

**Comment by jdnichollsc** [comment]
it looks like we can't https://stackoverflow.com/a/41226419/1532821

**Comment by redreceipt** [comment]
Ok thanks for looking `webview` it is then

**Comment by abendi** [comment]
I know it's a bit late, but thought I'd share an idea on how to pass cookies (session) into the browser. The idea is to use GET endpoint that adds `Set-Cookie` header to the response and then redirects to the target url.
On the native side you can for example base64 encode your cookies and target url, pass these as query parameters to your endpoint, decode parameters there, add cookies to response and do a redirect to the target url. Now the InAppBrowser has the cookies.

The security aspect of this solution is questionable though.

**Comment by jdnichollsc** [comment]
> I know it's a bit late, but thought I'd share an idea on how to pass cookies (session) into the browser. The idea is to manipulate headers (cookies) server-side. Implement a GET endpoint that adds `Set-Cookie` header to the response and then redirects to the target url. On the native side you can for example base64 encode your cookies and target url, pass these as query parameters to your endpoint, decode parameters there, add cookies to response and do a redirect to the target url. Now the InAppBrowser has the cookies. This also works on external browsers (opened via `Linking#openUrl`).
> 
> The security aspect of this solution is questionable though.

I forgot to say thanks for sharing that mate! <3

**Comment by abendi** [comment]
It's been some time now since my first proposed solution. I ended up with a token-based solution: client makes a POST request to back-end with request body of target url and cookies (because back-end does not know about cookie domain, expiration etc.). Back-end stores the url and cookies into a storage and returns a token to the client that can later be used in the InAppBrowser to read and use the stored values - back-end sets `Set-Cookie` header(s) and performs a redirect to the actual wanted url.
Using POST with request body instead of GET with url parameters is a bit more safe.

**Comment by GerardPolloRebozado** [comment]
Can you read cookies from the browser or only set them?
