### ISSUE TITLE
Android app getting crashed in release mode

### ISSUE THREAD

**Issue by kuljeetsingh31** [proyecto26/react-native-inappbrowser#15]
First of all thanks for your precious time.
Have installed latest plugin from npm repo but when building app it was giving below error:

/Users/kuljeetkakkar/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/95e09f6dccd9f5c14aba58f25aca898b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/fontVariationSettings not found.
    
/Users/kuljeetkakkar/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.1.1.aar/95e09f6dccd9f5c14aba58f25aca898b/res/values/values.xml:251:5-69: AAPT: error: resource android:attr/ttcIndex not found.
    
error: failed linking references.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processReleaseResources'.
> Failed to process resources, see aapt output above for details.

My Android Configurations is as follows:
buildToolsVersion = "27.0.3"
minSdkVersion = 16
compileSdkVersion = 27
targetSdkVersion = 26
supportLibVersion = "27.1.1"

Tried google the issue and found this https://stackoverflow.com/a/51474321.

So I changed my android configuration to
buildToolsVersion = "27.0.3"
minSdkVersion = 21
compileSdkVersion = 28
targetSdkVersion = 27
supportLibVersion = "28.0.0"

The build was successful with this. InAppBrowser worked perfectly when app is launched in debug mode.

But when tried the same in release mode the app crashed. Tested it on android 6 and android 7.

I have MI phone with android 7 which gave me the below error logs when the app crashed.

org.a.a.e: Subscriber class com.proyecto26.inappbrowser.b and its super classes have no public methods with the @Subscribe annotation
	at org.a.a.m.a(Unknown Source)
	at org.a.a.c.a(Unknown Source)
	at com.proyecto26.inappbrowser.b.a(Unknown Source)
	at com.proyecto26.inappbrowser.RNInAppBrowserModule.open(Unknown Source)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(Unknown Source)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(Unknown Source)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(Unknown Source)
	at android.os.Looper.loop(Looper.java:163)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:760)

_Originally posted by @kuljeetsingh31 in https://github.com/proyecto26/react-native-inappbrowser/issue_comments#issuecomment-437585642_

**Comment by kuljeetsingh31** [comment]
![inappbrowser](https://user-images.githubusercontent.com/7790212/48302191-30300380-e51f-11e8-8b98-cc7b1430a3af.jpeg)
Working perfectly in debug mode...

**Comment by jdnichollsc** [comment]
Honestly, I don't know
Can you try that configuration from the example folder of this repo?
Thanks and let me know

**Comment by jdnichollsc** [comment]
Try this and let me know https://github.com/proyecto26/react-native-inappbrowser/issues/11#issuecomment-436165385

**Comment by jdnichollsc** [comment]
On the other hand, I'm using this plugin in an app in Production (release mode)

**Comment by maestor** [comment]
I have this same stuff. After upgrade compileSdk and targetSdk to 28, build is fine, but crashes in production when try to open link to browser (debug won't do this and work).

I'm not expert, but think reason is those Android dependencies:
  implementation "com.android.support:support-annotations:+"
  implementation "com.android.support:customtabs:+"
  implementation 'org.greenrobot:eventbus:3.+'

This + is problematic because it took always latest version and it could be incompatible with different setups. These should have some sticky values which works (haven't find working ones yet).

Mine specs (didn't get build done at all with 27 ones because of this AAPT issue mentioned above):
buildToolsVersion = "28.0.2"
minSdkVersion = 19
compileSdkVersion = 28
targetSdkVersion = 28
supportLibVersion = "28.0.0"

Now looks like support modules working, but this eventbus throws some error when try to open link, report from play store:
org.greenrobot.eventbus.EventBusException: 
  at org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods (SubscriberMethodFinder.java:67)
  at org.greenrobot.eventbus.EventBus.register (EventBus.java:136)
  at com.proyecto26.inappbrowser.RNInAppBrowser.open (RNInAppBrowser.java:92)
  at com.proyecto26.inappbrowser.RNInAppBrowserModule.open (RNInAppBrowserModule.java:29)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:160)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:808)
  at android.os.Handler.dispatchMessage (Handler.java:101)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loop (Looper.java:166)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:192)
  at java.lang.Thread.run (Thread.java:784)

**Comment by maestor** [comment]
> Honestly, I don't know
> Can you try that configuration from the example folder of this repo?
> Thanks and let me know

That is now tested also that example will build and installed to phone with
```
react-native run-android --variant=release
```
but when I write some url and click button (= call open method), it crashes.

I can't get even clean debug version working with example. It will launch, but when I try to open some link, it crashes with "customtabs library not found" (which is natural behaviour because customtabs are excluded in example's build.gradle).

After I remove exclusion and force android.support dependencies to version 27.1.1 like supportLibVersion defined in example, it works with debug version. So example should have same #19 fix or its useless.

EDIT: After fixing android.support stuff, I got example working also in release mode! So have to continue research why I have this EventBus error when example don't have.

**Comment by maestor** [comment]
I found reason for why this EventBus error came (or at least how it can avoid). It relates somehow to Proguard. When I change enableProguardInReleaseBuilds from true to false I got release working, and when this Proguard minifying is enabled, release won't work. That explain also why it working in debug but not release.

I'm not expert about Proguard so don't know currently more why this happening, but workaround for others having same issue and nothing above have helped, just this in your app/build.gradle:

```
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false
```
Don't know either yet is there anything to do for permanent solution in this library side, needs googling and learning why Proguard minifying break that.

**Comment by jdnichollsc** [comment]
ohh but the React Native apps includes it by default:
```
/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
```

**Comment by jdnichollsc** [comment]
@maestor @kuljeetsingh31 sorry for the delay guys, check the last version from npm (1.3.7)
Thanks for the help! 👍

**Comment by maestor** [comment]
Thanks! Now it works like a charm without workarounds 👍 And good that you notice syntax errors also for build.gradle I accidentially left 😄 

In case somebody fight with Proguard and EventBus, it was easy to get that work also. Just add your proguard-rules.pro lines below:

```
  -keepattributes *Annotation*
  -keepclassmembers class ** {
    @org.greenrobot.eventbus.Subscribe <methods>;
   }
  -keep enum org.greenrobot.eventbus.ThreadMode { *; }
```

**Comment by kuljeetsingh31** [comment]
Works like a charm.... thanks a lot @jdnichollsc & @maestor

**Comment by pxmage** [comment]
> Thanks! Now it works like a charm without workarounds 👍 And good that you notice syntax errors also for build.gradle I accidentially left 😄
> 
> In case somebody fight with Proguard and EventBus, it was easy to get that work also. Just add your proguard-rules.pro lines below:
> 
> ```
>   -keepattributes *Annotation*
>   -keepclassmembers class ** {
>     @org.greenrobot.eventbus.Subscribe <methods>;
>    }
>   -keep enum org.greenrobot.eventbus.ThreadMode { *; }
> ```

You just saved my day! Thank you!

**Comment by mattop1709** [comment]
> Thanks! Now it works like a charm without workarounds 👍 And good that you notice syntax errors also for build.gradle I accidentially left 😄
> 
> In case somebody fight with Proguard and EventBus, it was easy to get that work also. Just add your proguard-rules.pro lines below:
> 
> ```
>   -keepattributes *Annotation*
>   -keepclassmembers class ** {
>     @org.greenrobot.eventbus.Subscribe <methods>;
>    }
>   -keep enum org.greenrobot.eventbus.ThreadMode { *; }
> ```

thanks mister! save my day tooo!
