### ISSUE TITLE
Redirect back to app with Firebase Dynamic Links

### ISSUE THREAD

**Issue by thecoorum** [proyecto26/react-native-inappbrowser#237]
### Please, provide the following version numbers that your issue occurs with:

- CLI: `react-native-cli: 2.0.1`
- Plugin(s): `3.5.1`

Is this possible to redirect back to the app with Firebase Dynamic Links? With `openAuth` and redirect to dynamic link that works from Safari/Notes, it just opens the fallback page in a browser

**Comment by jdnichollsc** [comment]
Please share a reproducible demo to debug your issue 🙂

**Comment by thecoorum** [comment]
@jdnichollsc I'm not sure that it's really possible, 'cause that should be the whole RN project with configured URL schemes
I can try to describe the issue a little more deeply

**Comment by thecoorum** [comment]
Basically, I just have installed and configured Firebase Dynamic Links to my app, so I can redirect to it with a regular HTTPS scheme (like `https://(domain).link.page/(endpoint)`). These links are properly working if I'll try to open them in Safari/Chrome or from the Notes app, but they are not working in `openAuth` method if I'll pass them both in `redirectUrl` and my website will redirect to this link

**Comment by jdnichollsc** [comment]
Can you share a log of the exception? I can't help you without that

**Comment by thecoorum** [comment]
There is no error, I was just asking is that possible

**Comment by jdnichollsc** [comment]
I can't help you without a reproducible demo to debug your scenario, sorry. Feel free to attach a GitHub repository to re-open your issue

**Comment by ErickMaeda** [comment]
Hello, 

The same issue happened with me. I was trying to use this library with both method `open()` and `openAuth()`

However the dynamic link is not being triggered, my approach was to use the simple `Linking.openUrl()`, it's not the best approach since the user is forced to leave the app to use the web browser, but it work's.

Linked issue: https://github.com/proyecto26/react-native-inappbrowser/issues/389
