### ISSUE TITLE
I need to auto redirect from browser to a screen once I get response

### ISSUE THREAD

**Issue by rishiankush** [proyecto26/react-native-inappbrowser#306]
I need to auto redirect to my page. I am using .then and navigating when I press on Done option, but instead I want the page to auto redirected. Is there any way I can do this.
My Implementation:
```
if (await InAppBrowser.isAvailable()) {
        InAppBrowser.open(res.data.links[1].href,{
          modalEnabled: false,
          forceCloseOnRedirection: true
        }).then((response)=>{
          console.log('repsonse paypal team ****** ',response);
          navigation.navigate('ThankYouPage',{orderId: res.orderId, payType: "PayPal", total: route.params.total})
        })
        .catch(error => {
          console.log('error ****** ',error);
        });
      }else{
        Linking.openURL(res.data.links[1].href)
      }
```

Here the .then method will only work on pressing the Done action. I want to navigate or redirect without pressing the Done button.

_Originally posted by @rishiankush in https://github.com/proyecto26/react-native-inappbrowser/issues/243#issuecomment-946662679_

**Comment by enlightenedpie** [comment]
> openAuth is the option to do that, or using deep linking redirection from the configuration of your app :)

I'd like to further elaborate on this, as I just ran into this issue myself and have a solution (and this issue is ranked at the top of Google search).

The `open` method of InAppBrowser doesn't automatically handle redirects like `openAuth` does, therefore you have to handle it yourself. For instance, in my app, we are opening a web page using `InAppBrowser.open(...)` where the user can perform some action, and when the user is done, the page redirects back to `my-custom-scheme://Home`. When this happens, `InAppBrowser` doesn't close even though the deep link worked properly.

@rishiankush What I did to solve this is use `Linking.addEventListener('url', doSomething)`, see [this](https://reactnative.dev/docs/linking#addeventlistener) for reference. In my specific case, using React Navigation, we added the event listener in the _[linking](https://reactnavigation.org/docs/deep-linking/#third-party-integrations)_ setup object. Where it lives in your app will depend on your routing and structure.

Within the `doSomething` function of that event listener, I close all instances of the InAppBrowser when there is a redirect to that specific deep link, using `InAppBrowser.close()`.

**Comment by jdnichollsc** [comment]
ohh sure, Linking is the best way to validate that directly, thanks for sharing mate! <3

**Comment by MayoudP** [comment]
Hello ! 
Did you managed redirection on your side ? I'm trying to set the `my-custom-scheme://Home`  as redirect URi in google cloud platform, but I'm having this error : Invalid redirect: Must use either http or https as the scheme. There is no way to do that ? 

Are we forced to use universal links ? 

Thanks for the help, and sorry for updating again the thread. My error is quite similar, or at least the usecase.
