### ISSUE TITLE
mailto link returns error

### ISSUE THREAD

**Issue by udarts** [proyecto26/react-native-inappbrowser#58]
Hi there,

I am using your plugin for my app, but in content we sometimes use a mailto link. This somehow is returning an error:

```
Exception 'The specified URL has an unsupported scheme. Only HTTP and HTTPS URLs are supported.' was thrown while invoking open on target RNInAppBrowser with params
```

No issues with http or https, but the mailto gives an issue.

Any idea how to fix this?

Cheers,
Stephan

**Comment by jdnichollsc** [comment]
mailto, tel, etc are with `Linking`

**Comment by Kikketer** [comment]
So I'm getting the same error but it's in an odd situation.  I have a WebView that has an `iframe` within it.  On iOS this exception is thrown if that `iframe` has a `src=""`.  The actual error says says that the RNInAppBrowser threw the error when provoking with the following params:

```
{
  dismissButtonStyle = close;
  readerMode = 0;
  url = "about:blank";
```

Obviously it doesn't support `about:` but the real question is why is this being thrown from an internal iframe within a WebView?  I'm working up a simplified example project now.

**Comment by jdnichollsc** [comment]
We are not using WebView, I don't understand

**Comment by Kikketer** [comment]
Exactly why I'm confused too, I think my trimmed up version will be telling.

**Comment by Kikketer** [comment]
Yep ignore me, it was an error on my side.  But in case you were wondering:

We have a WebView that could contain an iframe.  On the WebView we detect if the frame is attempting to navigate somewhere other than it's original domain, if it is then we launch using this library (otherwise keep it within the WebView).

Well come to find out an iframe inside a WebView triggers the same logic, even though the WebView itself isn't navigating.  So this iframe was triggering the `onShouldStartLoadWithRequest` of the WebView and the logic we have in there was saying to try and launch the iframe with InAppBrowser but the src was empty.

Just in case anyone else has similar issues, but really it's an education around WebView and it's hooks.
